[package]
name = "gtk-test"
version = "0.5.0"
authors = ["The Gtk-rs Project Developers"]
license = "MIT"
description = "Crate to test GTK UIs"
categories = ["api-bindings", "gui", "test"]
homepage = "http://gtk-rs.org/"
repository = "https://github.com/gtk-rs/gtk-test"
keywords = ["gtk", "gtk-rs", "GUI", "test", "gnome"]
documentation = "https://docs.rs/gtk-test"

[badges]
appveyor = { repository = "GuillaumeGomez/gtk-test", service = "github" }
travis-ci = { repository = "gtk-rs/gtk-test" }

[dependencies]
enigo = "^0.0.11"
gdk = "0.12.0"
glib = "0.9.0"
gtk = "0.8.0"

[[test]]
harness = false
name = "basic"

[[test]]
harness = false
name = "observer"
